apiVersion: v1
kind: Service
metadata:
  name: backend-b
  namespace: poc-networking
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  selector:
    app: backend-b
  ports:
    - port: 80
      targetPort: 3000

